version: '3'

volumes:
  django_sprint_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - django_sprint_data:/var/lib/postgresql/data
  backend:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - 8000:8000 
